desc = "Well-behaved and performant interpolation through points in 2D, 3D .. ManyD."
keywords = ["Catmull-Rom", "spline", "cubic", "interpolation", "centripetal"]
name = "CatmullRom"
uuid = "5b5b35a2-003c-5b99-bc04-a964994dd816"
repo = "https://github.com/JeffreySarnoff/CatmullRom.jl.git"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"
license = "MIT"
version = "v0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[targets]
test = ["Test", "Polynomials"]

[compat]
Polynomials = "0" 
